version: '3.3'
services:
  plexpy:
    image: "linuxserver/plexpy:latest"
    volumes:
      - /opt/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
      - /opt/plex/config:/config
    ports:
      - 8181:8181
  plex:
    image: "linuxserver/plex:latest"
    restart: unless-stopped
    env_file:
      - plex.env
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/transcode:/transcode
      - /opt/plex/data:/data
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp    
