version: '3.3'
services:
  plexpy:
    image: "linuxserver/plexpy:latest"
    volumes:
      - /opt/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
      - /opt/plex/config:/config
    ports:
      - "10002:8181"
  plex:
    image: "linuxserver/plex:latest"
    env_file:
      - plex.env
    volumes:
      - /opt/plex/config:/config
      - /opt/plex/transcode:/transcode
      - /opt/plex/data:/data
    ports:
      - "10005:32400"
    expose:
      - "32400"
